apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUit4N0RBRHIxMWd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01UWXhOalF3TXpKYUZ3MHpOVEEzTVRReE5qUTFNekphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURjN1A4THhLMXBWTDR6Kzc1YTN0U0pXbERDUE5kWUtabzdtZDdoZzA1dWJ5eHhpc29od0t0cXQ3T20Ka2M4WWhzWHlJYTZKZktGMVVKSzdyOGczaU5yMXpiaWdDTGRUZFl4RmRKOUtYWVpYYXNicW9wK1FJblpldTk4Nwp3RHcvblErRUFkYnpvQWJNS1hLZlc5YTlrYytZYXQwMFhiT1FoRm43SHBZS0k4TWJSS2wzMHdvZjRHd1EzOFAzClI1cUNoTWl4R2hZSHp1QjYzMUI4bmlWWW5LY3o4T2VDRnd1N3NERjlpUjZWeDJheE0zNGdqcHBZWVlKVThER3MKc3IvSEM1NWZqcldFVzhYei85MVhLZmkxdmJQc3hjcHV3MTR0S0tVZGJQNW9sbUdJTDdMVGN3TlJqVXdGZlg4NAphSkdRY0VHVU1YS2tjSlREWVcwaFZOdUgzSy9YQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTK29RVm9hSUZIYnlTZXJzYTd1Nzl1RU54WTNEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTJJb2lGdnBFcwpva2M2VEZ2UmdQczBwYS9tRVoxRnRqOUtqdnBWcmhXMmlHNVdBTlJWVmZaUm1oMFpTakw1L09KbmM0QmR0aDBQCk9zUTZTSmpGaXpQWkI3UnlTOUNDSHBoWmRENXBrSDhoVFFGdTlJYUJrcE9xNjY0Q3JNLzBYU1ZabEJDQzJSM2QKcVhVNk1JSEhjL3RKb2JiNW92MTlXdjl5TXdsWEk4TjJmUGFHK3h3TEFERnpIV3F4emRkZ1pjTkxYNGIyZjh0eQoxQ3F0ZlF6cDBrQ2o3OTBnTU5TVjRPVzhTMFRobXRNa1V0S2ozOWVTekxHWnhBdkh0V0w5UGR3REMwVHhJOGVyCkhGN3N6VElMMlg0Q2o5QUF1S3kxbGhtMnZiQmNvUFIvQ0IvL1c0MEtucnU4V2tJb1cwMUpQblV3dDN5dkt5M3oKUEp4QjFKWWJJMExxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://13581D9AFB7F1F9D6B5B6241F5F48605.gr7.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:234572319512:cluster/eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:234572319512:cluster/eks-cluster
    user: arn:aws:eks:eu-central-1:234572319512:cluster/eks-cluster
  name: arn:aws:eks:eu-central-1:234572319512:cluster/eks-cluster
current-context: arn:aws:eks:eu-central-1:234572319512:cluster/eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:234572319512:cluster/eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - eks-cluster
      - --output
      - json
      command: aws
